# Generated by Django 3.2 on 2021-10-15 15:53

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('1', 'ADMIN'), ('2', 'DOCENTE'), ('3', 'ESTUDIANTE')], default=1, max_length=20)),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=30, verbose_name='Ap. Paterno')),
                ('sur_name', models.CharField(blank=True, max_length=30, verbose_name='Ap. Materno')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('email_institucional', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('codigo_administrador', models.CharField(max_length=15, verbose_name='Codigo Administrador')),
                ('user_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='DNI')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('nombre_salon', models.CharField(max_length=10, null=True, verbose_name='Nombre de Salon')),
                ('tipo_aula', models.CharField(choices=[('T', 'Taller'), ('', 'Laboratorio'), ('E', 'Teoria')], max_length=20, verbose_name='Tipo de Aula')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('denominacion', models.CharField(max_length=100, verbose_name='Denominacion Ciclo')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('nro_ciclo_de_año', models.PositiveSmallIntegerField(verbose_name='Nro. Ciclo')),
                ('requisitos', models.TextField(verbose_name='Requisitos')),
                ('fecha_inicio_ciclo', models.DateField(null=True, verbose_name='Fecha inicio')),
                ('fecha_fin_ciclo', models.DateField(null=True, verbose_name='Fecha Culminacion')),
                ('fecha_inicio_preinscripcion', models.DateField(null=True, verbose_name='Fecha inicio preinscripcion')),
                ('fecha_fin_preinscripcion', models.DateField(null=True, verbose_name='Fecha final preinscripcion')),
                ('fecha_inicio_inscripcion', models.DateField(null=True, verbose_name='Fecha inicio inscripcion')),
                ('fecha_fin_inscripcion', models.DateField(null=True, verbose_name='Fecha final inscripcion')),
                ('numero_examenes', models.IntegerField(verbose_name='Nro. de examenes')),
                ('numero_maximo_cuotas', models.IntegerField(verbose_name='Nro. de cuotas maximo')),
                ('monto_colegio_privado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Colegio Privado')),
                ('monto_colegio_publico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Colegio Publico')),
                ('id_administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre_colegio', models.CharField(max_length=120, verbose_name='Nombre')),
                ('tipo_colegio', models.CharField(choices=[('PU', 'PUBLICO'), ('PR', 'PRIVADO')], max_length=2, verbose_name='Tipo Colegio')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='compromiso_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_vencimiento', models.DateField(null=True, verbose_name='Fecha vencimiento')),
            ],
            options={
                'verbose_name': 'Compromiso de Pago',
                'verbose_name_plural': 'Compromisos de Pagos',
            },
        ),
        migrations.CreateModel(
            name='detalle_compromiso_de_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('codigo_compromiso_pago', models.CharField(max_length=50, verbose_name='Codigo de pago')),
                ('numero_cuota', models.IntegerField(verbose_name='Nro. Cuota')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a pagar')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha limite')),
                ('esta_pagado', models.BooleanField(verbose_name='Pagado')),
                ('monto_mora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mora')),
                ('fecha_pagado', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('modalidad_pago', models.CharField(blank=True, max_length=40, null=True, verbose_name='Medio de pago')),
                ('id_compromiso_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compromiso_pago')),
            ],
            options={
                'verbose_name': 'Detalle Compromiso Pago',
                'verbose_name_plural': 'Detalles Compromisos de Pago',
                'unique_together': {('id_compromiso_pago', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('codigo_docente', models.CharField(max_length=20, verbose_name='Codigo Docente')),
                ('email_institucional', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('categoria', models.CharField(choices=[('P', 'Principal'), ('L', 'Locador'), ('A', 'Auxiliar'), ('C', 'Contratado')], max_length=1, verbose_name='Categoria Docente')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='escuela_profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre_escuela_profesional', models.CharField(max_length=40, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=10, verbose_name='Abreviacion')),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Escuela Profesional',
                'verbose_name_plural': 'Escuelas Profesionales',
            },
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('correo_institucional', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_examen', models.DateField(verbose_name='Fecha')),
                ('denominacion_examen', models.CharField(max_length=50, verbose_name='Denominacion')),
                ('tipo_examen', models.CharField(choices=[('PARCIAL', 'Parcial'), ('SIMULACRO', 'Simulacro'), ('CURSO', 'Curso especifico')], max_length=20, verbose_name='Tipo de examen')),
                ('nro_examen', models.IntegerField(verbose_name='Nro. de examen')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Final')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='grupo_academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('denominacion', models.CharField(max_length=40, verbose_name='Denominacion')),
                ('abreviacion', models.CharField(max_length=10, verbose_name='Abreviacion')),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Grupo Academico',
                'verbose_name_plural': 'Grupos Academicos',
            },
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aula')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciclo')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.docente')),
            ],
            options={
                'verbose_name': 'Curso ciclo',
                'verbose_name_plural': 'Cursos ciclo',
            },
        ),
        migrations.CreateModel(
            name='padron_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre_curso', models.CharField(max_length=50, verbose_name='Nombre del Curso')),
                ('abreviacion', models.CharField(max_length=10, verbose_name='Abreviacion')),
                ('descripcion', models.TextField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Padron de Cursos',
                'verbose_name_plural': 'Padron de Cursos',
            },
        ),
        migrations.CreateModel(
            name='padron_documento_requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=100, verbose_name='Nombre')),
                ('documento', models.FileField(upload_to='cargar_documentos', verbose_name='Subir archivo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado activo')),
            ],
            options={
                'verbose_name': 'Padron de Requisito Preinscripcion',
                'verbose_name_plural': 'Padron de Requisitos Preinscripcion',
            },
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nro_cuotas', models.IntegerField(verbose_name='Nro. de cuota(s)')),
                ('tipo_colegio', models.CharField(choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Publico')], max_length=10, verbose_name='Tipo de Colegio')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciclo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'unique_together': {('id', 'nro_cuotas')},
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('digito_verificador', models.CharField(blank=True, max_length=1, verbose_name='Digito Verificador')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Ap. Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Ap. Materno')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='tabla_configuraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validacion_telefono', models.BooleanField(verbose_name='Validar telefono')),
                ('validacion_email', models.BooleanField(verbose_name='Validar email')),
                ('mostrar_enlace_tesoreria', models.BooleanField(verbose_name='Monstrar enlace a tesoreria en Incripcion')),
                ('URL_tesoreria', models.URLField(verbose_name='Enlace a Tesoreria')),
                ('direccion_pago_fisico', models.CharField(max_length=200, null=True, verbose_name='Direccion de caja')),
                ('mostrar_pago_fisico', models.BooleanField(default=True, null=True, verbose_name='Mostrar pago fisico')),
                ('mostrar_pago_virtual', models.BooleanField(default=True, null=True, verbose_name='Mostrar pago virtual')),
            ],
        ),
        migrations.CreateModel(
            name='ubigeo',
            fields=[
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('codigo_ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Codigo Ubigeo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo_ubigeo', models.CharField(max_length=1, verbose_name='Tipo Ubigeo')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('denominacion_sede', models.CharField(max_length=50, verbose_name='Denominacion')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('id_ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubigeo')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='registro_tesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('esta_pagado', models.BooleanField(default=False, verbose_name='Esta pagado')),
                ('modalidad_pago', models.CharField(blank=True, max_length=40, null=True, verbose_name='Modalidad de pago')),
                ('fecha_pago', models.DateField(null=True, verbose_name='Fecha de pago')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_detalle_compromiso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.detalle_compromiso_de_pago')),
            ],
            options={
                'verbose_name_plural': 'Compromisos de pago tesoreria',
            },
        ),
        migrations.CreateModel(
            name='preinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('idioma', models.CharField(choices=[('ES', 'ESPAÑOL'), ('BO', 'BORA'), ('MA', 'MATSIGENKA'), ('SK', 'SHIPIBO-KONIBO')], max_length=30, null=True, verbose_name='Idioma')),
                ('progreso_preinscripcion', models.SmallIntegerField(default=1, null=True, verbose_name='Progreso Preinscripcion')),
                ('esta_enviado', models.BooleanField(default=False, null=True, verbose_name='Enviado')),
                ('telefono_apoderado', models.CharField(max_length=15, null=True, verbose_name='Telefono')),
                ('email_respaldo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de contacto')),
                ('dni_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciclo')),
                ('id_colegio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.colegio')),
                ('id_escuela_profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.escuela_profesional')),
                ('id_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pago')),
            ],
            options={
                'verbose_name': 'Preinscripcion',
                'verbose_name_plural': 'Preinscripciones',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubigeo'),
        ),
        migrations.CreateModel(
            name='padron_cursos_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('hora_semana', models.IntegerField(verbose_name='Horas a la semana')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado activo')),
                ('id_grupo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupo_academico')),
                ('id_padron_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.padron_curso')),
            ],
            options={
                'verbose_name': 'Padron cursos por grupo',
                'verbose_name_plural': 'Padron cursos por grupo',
            },
        ),
        migrations.CreateModel(
            name='pabellon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('denominacion_pabellon', models.CharField(max_length=50, verbose_name='Denominacion')),
                ('numero_pisos', models.IntegerField(verbose_name='Nro. de Pisos')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede')),
            ],
            options={
                'verbose_name': 'Pabellon',
                'verbose_name_plural': 'Pabellones',
            },
        ),
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('documentos', models.FileField(upload_to='cargar_documentos', verbose_name='Documentos')),
                ('id_compromiso_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.compromiso_pago')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='horario_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('dia_dictado', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sabado'), ('DOM', 'Domingo')], max_length=15)),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('id_horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
            options={
                'verbose_name': 'Horario Curso',
                'verbose_name_plural': 'Horario Cursos',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='id_padron_cursos_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.padron_cursos_grupo'),
        ),
        migrations.CreateModel(
            name='examen_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nota_promedio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Nota Promedio')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examen')),
            ],
            options={
                'verbose_name': 'Notas Estudiante',
                'verbose_name_plural': 'Notas Estudiantes',
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.padron_cursos_grupo'),
        ),
        migrations.CreateModel(
            name='estudiante_notas_por_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('notas_curso', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Nota')),
                ('id_examen_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examen_estudiante')),
                ('id_padron_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.padron_cursos_grupo')),
            ],
            options={
                'verbose_name': 'Notas Estudiante Por Curso',
                'verbose_name_plural': 'Notas Estudiantes Por Curso',
            },
        ),
        migrations.CreateModel(
            name='estudiante_horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.inscripcion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escuela_profesional',
            name='id_grupo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupo_academico'),
        ),
        migrations.CreateModel(
            name='documento_solicitado_ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciclo')),
                ('id_padron_documento_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.padron_documento_requisito')),
            ],
        ),
        migrations.CreateModel(
            name='documento_publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('descripcion', models.TextField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciclo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='id_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.persona'),
        ),
        migrations.CreateModel(
            name='detalle_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre_doc', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_doc', models.CharField(max_length=50, verbose_name='Tipo')),
                ('archivo', models.FileField(upload_to='cargar_documentos', verbose_name='Documento')),
                ('fecha_pub', models.DateField(verbose_name='Fecha Publicacion')),
                ('grupo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documento_publicacion')),
            ],
            options={
                'verbose_name': 'Detalle Documento',
                'verbose_name_plural': 'Detalle Documento',
            },
        ),
        migrations.AddField(
            model_name='compromiso_pago',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pago'),
        ),
        migrations.AddField(
            model_name='compromiso_pago',
            name='id_preinscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.preinscripcion'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='id_ubigeo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ubigeo'),
        ),
        migrations.AddField(
            model_name='aula',
            name='id_pabellon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pabellon'),
        ),
        migrations.CreateModel(
            name='asistencia_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante_horario')),
            ],
            options={
                'verbose_name': 'Asistencia Estudiante',
                'verbose_name_plural': 'Asistencias Estudiante',
            },
        ),
        migrations.CreateModel(
            name='asistencia_docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
            options={
                'verbose_name': 'Asistencia Docente',
                'verbose_name_plural': 'Asistencias Docente',
            },
        ),
        migrations.CreateModel(
            name='detalle_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nro_cuota', models.IntegerField(verbose_name='Nro. de cuota')),
                ('monto_parcial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Parcial')),
                ('monto_mora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Mora (%)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Final')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pago')),
            ],
            options={
                'verbose_name': 'Detalle Pago',
                'verbose_name_plural': 'Detalle Pagos',
                'unique_together': {('id_pago', 'nro_cuota')},
            },
        ),
    ]
