# Generated by Django 3.2 on 2021-10-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211015_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pago',
            name='especie_mora',
            field=models.CharField(choices=[('PORC', 'Porcentaje (%)'), ('FIJO', 'Monto fijo')], default='PORC', max_length=50, verbose_name='Tipo de mora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle_pago',
            name='monto_mora',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
