# Generated by Django 3.2 on 2021-10-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tabla_configuraciones_fuente_datos_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=5, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
