# Generated by Django 3.2 on 2021-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_preinscripcion_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscripcion',
            name='sexo',
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=5, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
