# Generated by Django 3.2 on 2021-10-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211018_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='id_ubigeo',
            field=models.ForeignKey(default='080000', on_delete=django.db.models.deletion.CASCADE, to='app.ubigeo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='digito_verificador',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Digito Verificador'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lugar_nacimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ubigeo'),
        ),
    ]
