# Generated by Django 3.2 on 2021-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211018_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
    ]
