# Generated by Django 3.2 on 2021-10-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211018_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ubigeo', verbose_name='Lugar actual de residencia'),
        ),
    ]
