# Generated by Django 3.2 on 2021-10-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211020_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='perfiles', verbose_name='Foto de perfil'),
        ),
    ]
