# Generated by Django 3.2 on 2021-10-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_estudiante_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento_solicitado_ciclo',
            options={'verbose_name_plural': 'Documentos Solicitado Inscripcion'},
        ),
        migrations.AlterModelOptions(
            name='padron_documento_requisito',
            options={'verbose_name': 'Padron de Requisito Inscripcion', 'verbose_name_plural': 'Padron de Requisitos Inscripcion'},
        ),
        migrations.RemoveField(
            model_name='documento_solicitado_ciclo',
            name='id_ciclo',
        ),
        migrations.RemoveField(
            model_name='padron_documento_requisito',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='padron_documento_requisito',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='padron_documento_requisito',
            name='nombre_documento',
        ),
        migrations.AddField(
            model_name='documento_solicitado_ciclo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion de requisito'),
        ),
        migrations.AddField(
            model_name='documento_solicitado_ciclo',
            name='documento',
            field=models.FileField(null=True, upload_to='cargar_documentos', verbose_name='Subir archivo'),
        ),
        migrations.AddField(
            model_name='documento_solicitado_ciclo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado activo'),
        ),
        migrations.AddField(
            model_name='documento_solicitado_ciclo',
            name='nombre_documento',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='padron_documento_requisito',
            name='id_ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ciclo'),
            preserve_default=False,
        ),
    ]
