# Generated by Django 3.2 on 2021-10-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211020_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='direccion',
            field=models.CharField(max_length=120, null=True, verbose_name='Direccion'),
        ),
    ]
