# Generated by Django 3.2 on 2021-10-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_preinscripcion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_colegio',
            field=models.CharField(choices=[('PR', 'Privado'), ('PU', 'Publico')], max_length=10, verbose_name='Tipo de Colegio'),
        ),
    ]
