# Generated by Django 3.2 on 2021-10-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_compromiso_pago_id_preinscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_solicitado_ciclo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='documento_solicitado_ciclo',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='documento_solicitado_ciclo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documento_solicitado_ciclo',
            name='nombre_documento',
        ),
        migrations.RemoveField(
            model_name='padron_documento_requisito',
            name='id_ciclo',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
        migrations.AddField(
            model_name='documento_solicitado_ciclo',
            name='id_ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ciclo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='padron_documento_requisito',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion de requisito'),
        ),
        migrations.AddField(
            model_name='padron_documento_requisito',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado activo'),
        ),
        migrations.AddField(
            model_name='padron_documento_requisito',
            name='nombre_documento',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre del documento'),
        ),
        migrations.AlterField(
            model_name='detalle_documento',
            name='archivo',
            field=models.FileField(upload_to='cargar_documentos/doc_academico', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciclo'),
        ),
    ]
