# Generated by Django 3.2 on 2021-10-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211025_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='nombre_salon',
        ),
        migrations.AddField(
            model_name='aula',
            name='nro_salon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre de Salon'),
        ),
    ]
