# Generated by Django 3.2 on 2021-10-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211025_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='monto_colegio_privado',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='monto_colegio_publico',
        ),
        migrations.AlterField(
            model_name='aula',
            name='nro_salon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nro. de Salon'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tipo_aula',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('LABO', 'Laboratorio'), ('TEORIA', 'Teoria')], max_length=20, verbose_name='Tipo de Aula'),
        ),
        migrations.AlterField(
            model_name='detalle_pago',
            name='monto_mora',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total'),
        ),
    ]
