# Generated by Django 3.2 on 2021-10-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211027_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tipo_colegio',
        ),
    ]
