# Generated by Django 3.2 on 2021-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211027_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pago',
            name='monto_mora',
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='monto_mora_privado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Priv'),
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='monto_mora_publico',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pub'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_total_privado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total Privado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_total_publico',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total Colegio Publico'),
        ),
        migrations.AlterField(
            model_name='detalle_pago',
            name='monto_parcial',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Parcial Privado'),
        ),
    ]
