# Generated by Django 3.2 on 2021-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211027_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_colegio',
            field=models.CharField(choices=[('PR', 'Privado'), ('PU', 'Publico')], default='PU', max_length=10, verbose_name='Tipo de Colegio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='idioma',
            field=models.CharField(choices=[('ES', 'ESPAÑOL'), ('BO', 'BORA'), ('MA', 'MATSIGENKA'), ('SK', 'SHIPIBO-KONIBO'), ('IN', 'INGLES')], max_length=30, null=True, verbose_name='Idioma'),
        ),
    ]
