# Generated by Django 3.2 on 2021-10-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20211027_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento_solicitado_ciclo',
            options={'verbose_name': 'Documento Solicitado Inscripcion', 'verbose_name_plural': 'Documentos Solicitado Inscripcion'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario de cursos', 'verbose_name_plural': 'Horario de curso'},
        ),
        migrations.AlterModelOptions(
            name='horario_curso',
            options={'verbose_name': 'Detalle Horario Curso', 'verbose_name_plural': 'Detalle Horario Cursos'},
        ),
    ]
