# Generated by Django 3.2 on 2021-10-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_padron_documento_requisito_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padron_documento_requisito',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripcion de requisito'),
        ),
        migrations.AlterField(
            model_name='padron_documento_requisito',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='docrequisitos', verbose_name='Subir documento'),
        ),
    ]
