# Generated by Django 3.2 on 2021-10-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20211027_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pago',
            options={'ordering': ['nro_cuota'], 'verbose_name': 'Detalle Pago', 'verbose_name_plural': 'Detalle Pagos'},
        ),
    ]
