# Generated by Django 3.2 on 2021-10-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_detalle_pago_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_compromiso_de_pago',
            options={'ordering': ['numero_cuota'], 'verbose_name': 'Detalle Compromiso Pago', 'verbose_name_plural': 'Detalles Compromisos de Pago'},
        ),
    ]
