# Generated by Django 3.2 on 2021-10-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_detalle_compromiso_de_pago_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colegio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudiante_horario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubigeo',
            options={},
        ),
    ]
