# Generated by Django 3.2 on 2021-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20211028_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento_publicacion',
            options={'verbose_name': 'Documento de Publicacion', 'verbose_name_plural': 'Documentos de Publicacion'},
        ),
        migrations.AddField(
            model_name='documento_publicacion',
            name='archivo',
            field=models.FileField(null=True, upload_to='', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='documento_publicacion',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='documento_publicacion',
            name='nombre_documento',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del archivo'),
        ),
        migrations.DeleteModel(
            name='detalle_documento',
        ),
    ]
