# Generated by Django 3.2 on 2021-10-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20211029_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclo',
            options={'verbose_name': 'Ciclo', 'verbose_name_plural': 'Ciclos'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterField(
            model_name='padron_curso',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
