# Generated by Django 3.2 on 2021-10-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20211029_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='numero_examenes',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='numero_maximo_cuotas',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='turno_mañana',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='turno_noche',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='turno_tarde',
        ),
    ]
