# Generated by Django 3.2 on 2021-10-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20211029_1628'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pago',
            unique_together={('id', 'id_ciclo')},
        ),
    ]
