# Generated by Django 3.2 on 2021-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_pago_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total'),
        ),
    ]
