# Generated by Django 3.2 on 2021-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_detalle_pago_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='condicion_discapacidad',
            field=models.BooleanField(default=False, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='detalle_discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especifique su discapacidad'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='nombres_apoderado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del apoderado'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='telefono_personal',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='telefono_apoderado',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono del apoderado'),
        ),
    ]
