# Generated by Django 3.2 on 2021-11-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20211105_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pago',
            name='especie_mora',
            field=models.CharField(choices=[('PORC', 'Porcentaje (%)'), ('FIJO', 'Monto fijo')], max_length=50, null=True, verbose_name='Tipo de mora'),
        ),
    ]
