# Generated by Django 3.2 on 2021-11-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_detalle_pago_especie_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='caja_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='requisitos',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
    ]
