# Generated by Django 3.2 on 2021-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20211108_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado_finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
