# Generated by Django 3.2 on 2021-11-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_inscripcion_estado_finalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'ordering': ['id'], 'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='asistencia_docente',
            options={'ordering': ['id'], 'verbose_name': 'Asistencia Docente', 'verbose_name_plural': 'Asistencias Docente'},
        ),
        migrations.AlterModelOptions(
            name='asistencia_estudiante',
            options={'ordering': ['id'], 'verbose_name': 'Asistencia Estudiante', 'verbose_name_plural': 'Asistencias Estudiante'},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['id'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='ciclo',
            options={'ordering': ['id'], 'verbose_name': 'Ciclo', 'verbose_name_plural': 'Ciclos'},
        ),
        migrations.AlterModelOptions(
            name='colegio',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='compromiso_pago',
            options={'ordering': ['id'], 'verbose_name': 'Compromiso de Pago', 'verbose_name_plural': 'Compromisos de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='detalle_compromiso_de_pago',
            options={'ordering': ['id'], 'verbose_name': 'Detalle Compromiso Pago', 'verbose_name_plural': 'Detalles Compromisos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['id'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='documento_publicacion',
            options={'ordering': ['id'], 'verbose_name': 'Documento de Publicacion', 'verbose_name_plural': 'Documentos de Publicacion'},
        ),
        migrations.AlterModelOptions(
            name='documento_solicitado_ciclo',
            options={'ordering': ['id'], 'verbose_name': 'Documento Solicitado Inscripcion', 'verbose_name_plural': 'Documentos Solicitado Inscripcion'},
        ),
        migrations.AlterModelOptions(
            name='documentos_inscripcion',
            options={'ordering': ['id'], 'verbose_name_plural': 'Documentos de Inscripcion'},
        ),
        migrations.AlterModelOptions(
            name='escuela_profesional',
            options={'ordering': ['id'], 'verbose_name': 'Escuela Profesional', 'verbose_name_plural': 'Escuelas Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['id'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='estudiante_horario',
            options={'ordering': ['id'], 'verbose_name': 'Horario de estudiante', 'verbose_name_plural': 'Horarios de estudiante'},
        ),
        migrations.AlterModelOptions(
            name='estudiante_notas_por_curso',
            options={'ordering': ['id'], 'verbose_name': 'Notas Estudiante Por Curso', 'verbose_name_plural': 'Notas Estudiantes Por Curso'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['id'], 'verbose_name': 'Examen', 'verbose_name_plural': 'Examenes'},
        ),
        migrations.AlterModelOptions(
            name='examen_estudiante',
            options={'ordering': ['id'], 'verbose_name': 'Notas Estudiante', 'verbose_name_plural': 'Notas Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='grupo_academico',
            options={'ordering': ['id'], 'verbose_name': 'Grupo Academico', 'verbose_name_plural': 'Grupos Academicos'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['id'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='horario_curso',
            options={'ordering': ['id'], 'verbose_name': 'Detalle Horario Curso', 'verbose_name_plural': 'Detalle Horario Cursos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['id'], 'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='pabellon',
            options={'ordering': ['id'], 'verbose_name': 'Pabellon', 'verbose_name_plural': 'Pabellones'},
        ),
        migrations.AlterModelOptions(
            name='padron_curso',
            options={'ordering': ['id'], 'verbose_name': 'Padron de Cursos', 'verbose_name_plural': 'Padron de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='padron_cursos_grupo',
            options={'ordering': ['id'], 'verbose_name': 'Padron cursos por grupo', 'verbose_name_plural': 'Padron cursos por grupo'},
        ),
        migrations.AlterModelOptions(
            name='padron_documento_requisito',
            options={'ordering': ['id'], 'verbose_name': 'Padron de Requisito Inscripcion', 'verbose_name_plural': 'Padron de Requisitos Inscripcion'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['id'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['id'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='preinscripcion',
            options={'ordering': ['id'], 'verbose_name': 'Preinscripcion', 'verbose_name_plural': 'Preinscripciones'},
        ),
        migrations.AlterModelOptions(
            name='registro_tesoreria',
            options={'ordering': ['id'], 'verbose_name_plural': 'Compromisos de pago tesoreria'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['id'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='tabla_configuraciones',
            options={'ordering': ['id'], 'verbose_name': 'Configuracion', 'verbose_name_plural': 'Configuraciones'},
        ),
    ]
