# Generated by Django 3.2 on 2021-11-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20211110_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='enlace_meet',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de sala virtual'),
        ),
        migrations.AlterField(
            model_name='horario_curso',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario'),
        ),
    ]
