# Generated by Django 3.2 on 2021-11-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20211110_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela_profesional',
            name='id_grupo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grupo_academico'),
        ),
    ]
