# Generated by Django 3.2 on 2021-11-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20211114_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia_estudiante',
            old_name='id_horario',
            new_name='id_estudiante_horario',
        ),
    ]
