# Generated by Django 3.2 on 2021-11-15 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_rename_id_horario_asistencia_estudiante_id_estudiante_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_estudiante',
            name='fecha_sesion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha sesion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia_estudiante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
    ]
