# Generated by Django 3.2 on 2021-11-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20211116_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='digito_verificador',
        ),
    ]
