# Generated by Django 3.2 on 2021-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20211123_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='codigo_modular',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Codigo modular'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='direccion_colegio',
            field=models.CharField(max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='ubigeo_nombre',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre ubigeo'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='nombre_colegio',
            field=models.CharField(max_length=180, verbose_name='Nombre'),
        ),
    ]
