# Generated by Django 3.2 on 2021-11-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20211124_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='id_persona',
        ),
    ]
