# Generated by Django 3.2 on 2021-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_docente_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela_profesional',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviacion'),
        ),
        migrations.AlterField(
            model_name='escuela_profesional',
            name='codigo_escuela',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='escuela_profesional',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
