# Generated by Django 3.2 on 2021-11-26 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20211124_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='padron_cursos_grupo',
            name='nro_preguntas_examen',
            field=models.PositiveIntegerField(default=0, verbose_name='Preguntas para examen'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='material_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('descripcion_material', models.TextField(verbose_name='Descripcion')),
                ('enlace_recurso', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='materiales', verbose_name='Archivo')),
                ('tipo_recurso', models.CharField(choices=[('AVISO', 'AVISO'), ('RECURSO', 'RECURSO')], max_length=10, verbose_name='Tipo')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
            options={
                'verbose_name': 'Material de clase',
                'verbose_name_plural': 'Materiales de clase',
                'ordering': ('-fecha_registro',),
            },
        ),
        migrations.CreateModel(
            name='comentarios_clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('texto_comentario', models.TextField(verbose_name='Comentario')),
                ('archivo_adjunto', models.FileField(upload_to='archivos_clase', verbose_name='Archivo adjunto')),
                ('id_docente', models.CharField(max_length=100, verbose_name='Docente')),
                ('id_estudiante', models.CharField(max_length=100, verbose_name='Estudiante')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
            options={
                'verbose_name': 'Comentario de clase',
                'verbose_name_plural': 'Comentarios de clase',
                'ordering': ('-fecha_registro',),
            },
        ),
        migrations.CreateModel(
            name='balota_preguntas_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('texto_pregunta', models.TextField(verbose_name='Pregunta')),
                ('img_pregunta', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.docente')),
                ('id_padron_curso_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.padron_cursos_grupo')),
            ],
            options={
                'verbose_name': 'Preguntas de balotario',
                'verbose_name_plural': 'Balotario',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='alternativas_balotario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('texto_alternativa', models.TextField(verbose_name='Alternativa')),
                ('es_respuesta', models.BooleanField(verbose_name='Respuesta')),
                ('id_balota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.balota_preguntas_curso')),
            ],
            options={
                'verbose_name': 'Alternativas',
                'ordering': ('id',),
            },
        ),
    ]
