# Generated by Django 3.2 on 2021-11-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_comentarios_clase_archivo_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_clase',
            name='id_estudiante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudiante'),
        ),
    ]
