# Generated by Django 3.2 on 2021-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_comentarios_clase_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_clase',
            name='id_docente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Docente'),
        ),
    ]
