# Generated by Django 3.2 on 2021-11-29 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_comentarios_clase_id_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='tipo_aula',
            field=models.CharField(blank=True, choices=[('TALLER', 'Taller'), ('LABO', 'Laboratorio'), ('TEORIA', 'Teoria')], max_length=20, null=True, verbose_name='Tipo de Aula'),
        ),
        migrations.AlterField(
            model_name='pabellon',
            name='id_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sede'),
        ),
    ]
