# Generated by Django 3.2 on 2021-11-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20211129_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos_inscripcion',
            old_name='esta_aprovado',
            new_name='esta_aprobado',
        ),
        migrations.RenameField(
            model_name='documentos_inscripcion_revision',
            old_name='esta_aprovado',
            new_name='esta_aprobado',
        ),
    ]
