# Generated by Django 3.2 on 2021-11-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20211129_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_inscripcion_revision',
            name='id_administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='registro_tesoreria',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.administrador'),
        ),
    ]
