# Generated by Django 3.2 on 2021-11-29 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20211129_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tipo usuario'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tipo de usuario'),
        ),
    ]
