# Generated by Django 3.2 on 2021-12-02 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20211129_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Tipo usuario'),
        ),
        migrations.AlterField(
            model_name='alternativas_balotario',
            name='id_balota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.balota_preguntas_curso'),
        ),
        migrations.AlterField(
            model_name='asistencia_docente',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.horario'),
        ),
        migrations.AlterField(
            model_name='asistencia_estudiante',
            name='id_estudiante_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudiante_horario'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='id_pabellon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pabellon'),
        ),
        migrations.AlterField(
            model_name='balota_preguntas_curso',
            name='id_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.docente'),
        ),
        migrations.AlterField(
            model_name='balota_preguntas_curso',
            name='id_padron_curso_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.padron_cursos_grupo'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='id_administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='comentarios_clase',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.horario'),
        ),
        migrations.AlterField(
            model_name='compromiso_pago',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pago'),
        ),
        migrations.AlterField(
            model_name='compromiso_pago',
            name='id_preinscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.preinscripcion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='detalle_compromiso_de_pago',
            name='id_compromiso_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.compromiso_pago'),
        ),
        migrations.AlterField(
            model_name='detalle_pago',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pago'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='documento_publicacion',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ciclo'),
        ),
        migrations.AlterField(
            model_name='documento_solicitado_ciclo',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ciclo'),
        ),
        migrations.AlterField(
            model_name='documento_solicitado_ciclo',
            name='id_padron_documento_requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.padron_documento_requisito'),
        ),
        migrations.AlterField(
            model_name='documentos_inscripcion',
            name='id_inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.inscripcion'),
        ),
        migrations.AlterField(
            model_name='documentos_inscripcion_revision',
            name='id_administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='documentos_inscripcion_revision',
            name='id_documento_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.documentos_inscripcion'),
        ),
        migrations.AlterField(
            model_name='escuela_profesional',
            name='id_grupo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.grupo_academico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.inscripcion'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudiante_horario',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante_horario',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.horario'),
        ),
        migrations.AlterField(
            model_name='estudiante_notas_por_curso',
            name='id_examen_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.examen_estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante_notas_por_curso',
            name='id_padron_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.padron_cursos_grupo'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ciclo'),
        ),
        migrations.AlterField(
            model_name='examen_estudiante',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudiante'),
        ),
        migrations.AlterField(
            model_name='examen_estudiante',
            name='id_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.examen'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='id_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.aula'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ciclo'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='id_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.docente'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='id_padron_cursos_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.padron_cursos_grupo'),
        ),
        migrations.AlterField(
            model_name='horario_curso',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.horario'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_compromiso_pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.compromiso_pago'),
        ),
        migrations.AlterField(
            model_name='material_curso',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.horario'),
        ),
        migrations.AlterField(
            model_name='pabellon',
            name='id_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.sede'),
        ),
        migrations.AlterField(
            model_name='padron_cursos_grupo',
            name='id_grupo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.grupo_academico'),
        ),
        migrations.AlterField(
            model_name='padron_cursos_grupo',
            name='id_padron_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.padron_curso'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ciclo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lugar_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.ubigeo', verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='dni_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.persona'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ciclo'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.colegio'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_escuela_profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.escuela_profesional'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.pago'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.ubigeo', verbose_name='Lugar actual de residencia'),
        ),
        migrations.AlterField(
            model_name='registro_tesoreria',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='registro_tesoreria',
            name='id_detalle_compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.detalle_compromiso_de_pago'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='id_ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.ubigeo'),
        ),
    ]
