# Generated by Django 3.2 on 2021-12-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20211202_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_clase',
            name='id_docente',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.docente'),
        ),
        migrations.AlterField(
            model_name='comentarios_clase',
            name='id_estudiante',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.estudiante'),
        ),
    ]
