# Generated by Django 3.2 on 2021-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_examen_grupo_preguntas_examen_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_grupo',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
